# Plot joli RMSE

In [1]:
import json
import glob
import os
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:

database_list = [
    "/Odyssey/private/j25lee/glonet/gradient_descent_optimic/outputs/forecast_exp/idx3_but0_perfect_obs_20260506_220634",
    "/Odyssey/private/j25lee/glonet/gradient_descent_optimic/outputs/forecast_exp/idx0_but0_osse_obs_20260508_164728",
    "/Odyssey/private/j25lee/glonet/gradient_descent_optimic/outputs/forecast_exp/idx3_but-3_fullobs_20260510_180947",
    "/Odyssey/private/j25lee/glonet/gradient_descent_optimic/outputs/forecast_exp/osse_uncertainIC_idx0_but3_20260519_110445"
]
output_path = "/Odyssey/private/j25lee/glonet/gradient_descent_optimic/outputs/forecast_exp/"
output_file = "rmse_conclusion.csv"

In [4]:
from IPython.display import display

def load_rmse_tables(exp_path, region="global"):
    rmse_path = Path(exp_path) / "rmse_regional_analysis.json"
    with rmse_path.open() as handle:
        data = json.load(handle)

    steps = data["metadata"]["steps"]
    variables = data["metadata"]["channel_names"]
    reference = np.array(data["reference_rmse"][region], dtype=float)
    optimized = np.array(data["optimized_rmse"][region], dtype=float)

    gain_abs = reference - optimized
    with np.errstate(divide="ignore", invalid="ignore"):
        gain_pct = np.where(reference != 0, gain_abs / reference * 100.0, np.nan)

    gain_abs_df = pd.DataFrame(gain_abs, index=steps, columns=variables)
    gain_pct_df = pd.DataFrame(gain_pct, index=steps, columns=variables)
    return gain_abs_df, gain_pct_df

region_name = "global"

tables = []
for exp_path in database_list:
    gain_abs_df, gain_pct_df = load_rmse_tables(exp_path, region=region_name)
    exp_name = Path(exp_path).name
    print(f"\n=== {exp_name} | region={region_name} ===")
    display(gain_abs_df)
    display(gain_pct_df)

    gain_abs_long = gain_abs_df.copy()
    gain_abs_long["metric"] = "gain_abs"
    gain_pct_long = gain_pct_df.copy()
    gain_pct_long["metric"] = "gain_pct"
    merged = pd.concat([gain_abs_long, gain_pct_long])
    merged["experiment"] = exp_name
    merged["region"] = region_name
    merged["step"] = merged.index
    tables.append(merged)

if tables:
    output_df = pd.concat(tables, ignore_index=True)
    output_full_path = Path(output_path) / output_file
    output_full_path.parent.mkdir(parents=True, exist_ok=True)
    output_df.to_csv(output_full_path, index=False)
    print(f"Saved: {output_full_path}")

=== idx3_but0_perfect_obs_20260506_220634 | region=global ===

         SSH    thetao        so        uo        vo
1  -0.004726 -0.000181 -0.000555 -0.003326 -0.003865
2   0.002827  0.010458  0.004420  0.001920  0.005099
3   0.010610  0.034209  0.014044  0.005798  0.015219
4   0.011089  0.056108  0.024830  0.011811  0.023542
5   0.015994  0.082442  0.034733  0.019630  0.033092
6   0.020692  0.106201  0.046631  0.026827  0.042276
7   0.025232  0.124218  0.053516  0.031900  0.048389
8   0.029065  0.130950  0.064592  0.034505  0.050850
9   0.028295  0.130140  0.066068  0.032603  0.043237
10  0.024792  0.125246  0.065508  0.031588  0.038501
11  0.022099  0.120283  0.056610  0.026890  0.033049
12  0.020224  0.117739  0.049744  0.023571  0.027775
13  0.020400  0.117023  0.047544  0.022119  0.023543
14  0.019364  0.117831  0.046656  0.016700  0.019865
15  0.018366  0.117311  0.044900  0.014646  0.018143
16  0.016721  0.115359  0.045726  0.012597  0.016751
17  0.016690  0.110269  0.044599  0.009664  0.013426
18  0.016609  0.109160  0.036477  0.007662  0.010645
19  0.015745  0.110448  0.035420  0.005074  0.008226
20  0.014822  0.110016  0.033534  0.005634  0.006477
21  0.014593  0.111013  0.033332  0.005360  0.005611
22  0.013760  0.106490  0.034490  0.006262  0.003840
23  0.013259  0.102531  0.035261  0.006640  0.002724
24  0.012487  0.100179  0.035711  0.004974  0.001417
25  0.012161  0.098171  0.033437  0.004814 -0.000567
26  0.012892  0.098977  0.034290  0.006058 -0.000212
27  0.013259  0.099277  0.033864  0.005227 -0.000165
28  0.013212  0.100353  0.030468  0.004679 -0.000802

          SSH     thetao         so         uo         vo
1         NaN        NaN        NaN        NaN        NaN
2   15.159174   4.663996   4.747711   3.433129   8.863304
3   31.371555   9.207136   9.614747   7.730636  19.091427
4   28.105388  11.542513  13.496177  13.307670  25.116517
5   34.000605  14.191573  16.082100  19.400989  30.834623
6   37.750156  15.785796  18.835088  23.546767  35.579619
7   39.683544  16.526302  19.520144  25.600600  37.511682
8   40.417838  15.937335  21.418137  25.617376  36.879391
9   36.278846  14.647917  20.435391  22.566649  29.755511
10  29.209041  13.186439  19.084441  20.550963  25.136427
11  24.061375  11.898496  15.888258  16.533376  20.729839
12  20.580226  10.980803  13.407104  13.947565  16.686023
13  19.783395  10.310380  12.194896  12.603566  13.679862
14  17.997374   9.801781  11.554877   9.232912  11.271403
15  16.294479   9.244021  10.704432   7.802027  10.118423
16  14.133416   8.624154  10.514668   6.527183   9.081004
17  13.621761   7.859206   9.997193   4.928181   7.156972
18  13.069275   7.423677   7.988134   3.835091   5.594754
19  11.948017   7.159786   7.519255   2.489907   4.280016
20  10.831117   6.807119   6.893258   2.746793   3.354206
21  10.311000   6.556391   6.657002   2.587018   2.874100
22   9.345418   6.014090   6.680115   2.969962   1.954135
23   8.638158   5.543199   6.645510   3.099990   1.386062
24   7.862982   5.188717   6.562854   2.306552   0.717331
25   7.450064   4.875162   6.032583   2.221627  -0.286021
26   7.640747   4.706013   6.044214   2.772305  -0.106524
27   7.599117   4.518159   5.772070   2.358889  -0.082353
28   7.279077   4.372920   5.104568   2.095052  -0.397088

=== idx0_but0_osse_obs_20260508_164728 | region=global ===

         SSH    thetao        so        uo        vo
1  -0.004046 -0.000122 -0.000156 -0.001961 -0.002291
2  -0.000438  0.008123 -0.003024 -0.003430 -0.004210
3   0.000330  0.012667 -0.008360 -0.002471 -0.004387
4  -0.000625  0.026389 -0.012879  0.000382 -0.004049
5  -0.004084  0.043428 -0.017620  0.000788 -0.002096
6   0.000913  0.061880 -0.015727  0.003834 -0.001079
7   0.006234  0.078678 -0.018310  0.004141 -0.000725
8   0.009990  0.093263 -0.015763  0.004500 -0.000519
9   0.010429  0.097156 -0.015224  0.004970 -0.000705
10  0.010216  0.097206 -0.015053  0.005447 -0.000885
11  0.010141  0.096596 -0.016960  0.009374  0.000293
12  0.010830  0.095022 -0.017463  0.011134 -0.000423
13  0.010166  0.092294 -0.019316  0.014859  0.001525
14  0.009403  0.087737 -0.021232  0.014791  0.002679
15  0.009116  0.081661 -0.019326  0.016015  0.002666
16  0.008306  0.073069 -0.015313  0.016198  0.002761
17  0.006813  0.064616 -0.014547  0.015265  0.002193
18  0.006649  0.057549 -0.007683  0.014436  0.003052
19  0.005560  0.049978 -0.008838  0.014024  0.002364
20  0.004744  0.041301 -0.011309  0.014371  0.001107
21  0.004378  0.034088 -0.012448  0.014805  0.002183
22  0.003734  0.026776 -0.011047  0.014321  0.001340
23  0.002729  0.017891 -0.012443  0.013024  0.000543
24  0.001459  0.009564 -0.013586  0.012312  0.001039
25  0.001494  0.003104 -0.011408  0.010879  0.000425
26  0.001510 -0.005778 -0.011146  0.009277 -0.000709
27  0.000268 -0.016576 -0.012706  0.007957 -0.000835
28 -0.000915 -0.030883 -0.011299  0.007366 -0.001448

          SSH     thetao        so        uo        vo
1         NaN        NaN       NaN       NaN       NaN
2   -2.245547   3.738219 -3.376251 -6.252162 -7.559762
3    1.120932   3.596112 -5.920963 -3.331197 -5.627433
4   -1.553711   5.699686 -7.155415  0.417596 -4.364221
5   -8.263431   7.722722 -8.232835  0.764226 -1.917078
6    1.595560   9.485854 -6.472338  3.345792 -0.901996
7   10.124127  10.690654 -6.825887  3.340570 -0.565678
8   14.712175  11.399847 -5.362504  3.344544 -0.374564
9   13.986420  10.838460 -4.914091  3.442505 -0.484555
10  12.571464  10.053267 -4.544232  3.565642 -0.580040
11  11.446671   9.337843 -4.828988  5.739210  0.183921
12  11.462261   8.639670 -4.753128  6.449814 -0.255765
13  10.057606   7.950884 -5.005603  8.121601  0.892236
14   8.771162   7.189696 -5.350932  7.800752  1.519923
15   8.084258   6.369772 -4.716135  8.171786  1.473075
16   7.105114   5.439978 -3.573717  8.050620  1.486790
17   5.657387   4.593666 -3.271327  7.357808  1.158510
18   5.305297   3.906599 -1.675725  6.816502  1.596314
19   4.269199   3.238492 -1.869025  6.489593  1.224363
20   3.540144   2.561521 -2.344293  6.568318  0.568208
21   3.135181   2.025280 -2.514255  6.678207  1.110604
22   2.582612   1.522582 -2.166779  6.355105  0.677674
23   1.824248   0.974307 -2.372476  5.802482  0.274209
24   0.945692   0.498079 -2.520217  5.482225  0.521235
25   0.929185   0.154464 -2.060535  4.809598  0.211553
26   0.903978  -0.275492 -1.962512  4.081669 -0.354107
27   0.156236  -0.758381 -2.197126  3.510040 -0.414552
28  -0.520854  -1.357412 -1.901043  3.250503 -0.716036

=== idx3_but-3_fullobs_20260510_180947 | region=global ===

         SSH    thetao        so        uo        vo
1   0.000562  0.000104  0.000365  0.000106  0.000088
2   0.007244  0.026216  0.013211  0.002119  0.002500
3   0.006120  0.050727  0.018900  0.003323  0.003961
4   0.011729  0.079269  0.025942  0.006810  0.009223
5   0.016112  0.106738  0.033506  0.014416  0.017446
6   0.019107  0.130380  0.042200  0.023145  0.027845
7   0.024836  0.151853  0.048704  0.029838  0.035298
8   0.025954  0.157807  0.055977  0.033631  0.040401
9   0.023014  0.157082  0.053190  0.034085  0.040533
10  0.021612  0.149744  0.049301  0.033042  0.036186
11  0.020467  0.147450  0.045497  0.030580  0.029170
12  0.020506  0.147373  0.044433  0.028912  0.025387
13  0.019939  0.148355  0.045963  0.027787  0.022844
14  0.018716  0.146559  0.042778  0.023478  0.018459
15  0.017008  0.145840  0.042798  0.021465  0.015687
16  0.016095  0.139344  0.039022  0.020451  0.014133
17  0.014922  0.132299  0.032863  0.019184  0.011781
18  0.014833  0.125653  0.025606  0.019098  0.009463
19  0.013568  0.121636  0.024280  0.019490  0.007612
20  0.012416  0.118557  0.021698  0.018677  0.006285
21  0.011517  0.114486  0.019657  0.017435  0.004768
22  0.010535  0.108580  0.021273  0.016850  0.004083
23  0.009492  0.101586  0.019391  0.014100  0.003617
24  0.009305  0.094127  0.019670  0.011876  0.002578
25  0.009784  0.089196  0.013165  0.010848  0.002969
26  0.009958  0.080069  0.011021  0.009531  0.001615
27  0.008823  0.070543  0.005758  0.008766  0.002405
28  0.007773  0.060669  0.004713  0.008699  0.002928

          SSH     thetao         so         uo         vo
1    1.292442   0.023870   0.188008   0.098891   0.076863
2   17.815861   5.372518   6.488749   2.238340   2.564299
3   15.604591   9.271966   8.878444   3.787363   4.468630
4   27.107086  12.880658  11.249329   7.734049  10.326058
5   32.639227  15.434825  13.368158  14.940343  18.404705
6   33.566246  17.136312  15.387434  21.334723  26.280599
7   37.801272  18.326395  16.609340  24.380034  29.661863
8   36.661184  17.705854  17.786548  25.238160  30.997571
9   29.814032  16.577587  16.257789  23.527353  28.687617
10  25.546273  14.914895  14.530578  21.262688  24.152839
11  22.431292  13.877001  12.902961  18.630861  18.426386
12  21.266523  13.151420  11.956752  16.854472  15.369440
13  19.783248  12.538351  11.801132  15.309160  13.340973
14  17.609009  11.758639  10.637423  12.568250  10.677584
15  15.110156  11.124737  10.230617  11.071712   8.847235
16  13.829924  10.168884   9.072746  10.303229   7.738210
17  12.390221   9.256654   7.385500   9.467811   6.350834
18  11.861371   8.415291   5.598799   9.193236   5.039751
19  10.455054   7.796731   5.154388   9.260036   4.005418
20   9.243696   7.262285   4.473200   8.755370   3.265596
21   8.200953   6.705276   3.936770   8.041002   2.452100
22   7.197103   6.093298   4.131108   7.613859   2.086284
23   6.284152   5.472663   3.674148   6.379677   1.834559
24   5.998809   4.870811   3.640325   5.388012   1.292723
25   6.077184   4.423520   2.384549   4.891541   1.476497
26   5.978825   3.810315   1.936064   4.250742   0.799200
27   5.105027   3.223121   0.997003   3.878844   1.171960
28   4.306643   2.661260   0.794997   3.807499   1.411848

=== osse_uncertainIC_idx0_but3_20260519_110445 | region=global ===

         SSH    thetao        so        uo        vo
1  -0.004779 -0.000157 -0.000194 -0.002279 -0.002677
2  -0.003179  0.009999 -0.005878 -0.002697 -0.002774
3  -0.000813  0.023326 -0.011389 -0.001833 -0.001425
4  -0.004545  0.034893 -0.016935  0.000935 -0.001533
5  -0.003450  0.050976 -0.022110  0.004170  0.001366
6   0.002302  0.066886 -0.019209  0.006372  0.002486
7   0.006650  0.081851 -0.017979  0.007729  0.003078
8   0.011866  0.094111 -0.013397  0.008576  0.004537
9   0.013558  0.096328 -0.010694  0.006309  0.002666
10  0.013819  0.094866 -0.007700  0.006062  0.002107
11  0.012829  0.093025 -0.008701  0.006780  0.003013
12  0.013451  0.090846 -0.006675  0.007834  0.003353
13  0.012061  0.086149 -0.011614  0.009582  0.003731
14  0.011274  0.081389 -0.014876  0.009029  0.004337
15  0.010298  0.075242 -0.011817  0.008472  0.003541
16  0.010137  0.071790 -0.013096  0.008291  0.003890
17  0.009197  0.067137 -0.010807  0.008793  0.003896
18  0.008443  0.063951 -0.016515  0.008980  0.003010
19  0.007623  0.060013 -0.017420  0.007191  0.002467
20  0.007381  0.058258 -0.014983  0.007878  0.002012
21  0.006710  0.056855 -0.012847  0.008060  0.001529
22  0.005873  0.049634 -0.014060  0.008589  0.000854
23  0.005481  0.042564 -0.013820  0.009320  0.000058
24  0.004436  0.035476 -0.012741  0.009475  0.000030
25  0.003483  0.026654 -0.013100  0.009570 -0.001351
26  0.002929  0.018744 -0.013291  0.009257 -0.002005
27  0.002779  0.011101 -0.013382  0.008107 -0.001728
28  0.002371  0.005877 -0.013609  0.006197 -0.002552

          SSH     thetao         so        uo        vo
1         NaN        NaN        NaN       NaN       NaN
2   -8.091853   2.786889  -3.924408 -2.720099 -2.659151
3   -2.106939   6.409559  -8.113042 -1.745608 -1.291672
4  -10.322411   8.672737 -11.866597  0.834241 -1.302066
5   -6.660878  10.252627 -12.441978  3.512760  1.081202
6    3.860242  11.180071  -8.803315  5.033836  1.876636
7   10.420189  11.891148  -7.170509  5.766999  2.214937
8   16.771837  12.204939  -4.753659  6.041170  3.092215
9   17.407700  11.270974  -3.493792  4.251049  1.758373
10  16.318327  10.207085  -2.324883  3.919602  1.344064
11  14.006600   9.303741  -2.465907  4.181628  1.867726
12  13.862716   8.520490  -1.786464  4.600109  2.008303
13  11.719749   7.635292  -2.978578  5.351955  2.161780
14  10.326963   6.838913  -3.704110  4.902223  2.434538
15   8.970487   6.006265  -2.844493  4.496622  1.929479
16   8.491585   5.443858  -3.018719  4.307818  2.072145
17   7.462575   4.841647  -2.408268  4.422563  2.037825
18   6.616609   4.387510  -3.605697  4.415827  1.571929
19   5.738219   3.918119  -3.690709  3.479795  1.271371
20   5.387203   3.628159  -3.088885  3.762488  1.028904
21   4.737703   3.382806  -2.585927  3.802596  0.779999
22   4.021008   2.824418  -2.749754  3.981654  0.435338
23   3.619338   2.316811  -2.620769  4.306089  0.029469
24   2.835354   1.844949  -2.344919  4.359635  0.015404
25   2.140410   1.324683  -2.356028  4.346386 -0.683342
26   1.728878   0.891225  -2.332236  4.172545 -1.018592
27   1.586362   0.505360  -2.291827  3.642815 -0.870534
28   1.320271   0.256342  -2.281553  2.785707 -1.280351

Saved: /Odyssey/private/j25lee/glonet/gradient_descent_optimic/outputs/forecast_exp/rmse_conclusion.csv